### ISSUE TITLE
normalization of resnet12 and convnet

### ISSUE THREAD

**Issue by buptxiaofeng** [Han-Jia/UNICORN-MAML#6]
Hi, thanks for sharing this impressive work. I notice that in the implementation of dataloaders, the normalization of convnet and resnet are using different values? Are there any reasons for this?

**Comment by Han-Jia** [comment]
Hi,

Since there are no standard values for ConvNet, we set the normalization values of ConvNet the same as those for ImageNet. Similarly for ResNet18/50. While for ResNet12, we follow [MetaOptNet](https://github.com/kjunelee/MetaOptNet/blob/0b35aaf0ded382b046e2bc5adc3c88c3fe6ccd1a/data/mini_imagenet.py#L125) to set the normalization values, in which the ResNet12 is designed.
